Repository boostcampwm-2021/WEB26-COKIRI, pull requests merged in 2021-12, with the labels that each got.

#236 이미지 로딩 시 스켈레톤 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/style.ts
  frontend/src/components/SkeletonLoading/index.tsx
  frontend/src/components/cards/DashboardBasicCard/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/ProfileImage/index.tsx
  frontend/src/components/images/ProfileImage/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/home.tsx
Labels: FE

#237 Fix: 타입 기입 오류로인한 버그 수정
  frontend/src/components/mains/RandomMain/index.tsx
  frontend/src/utils/Fetcher.ts
Labels: FIX, FE

#238 react-virtualized를 통한 무한 스크롤 렌더링 최적화 👍
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/PostDetail/style.ts
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/Timeline/style.ts
  frontend/src/components/contents/ExternalContent/index.tsx
  frontend/src/components/contents/NormalContent/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/mains/HomeMain/index.tsx
  frontend/src/components/mains/RandomMain/index.tsx
  frontend/src/components/mains/UserMain/index.tsx
  frontend/src/styles/global.ts
Labels: FEAT, FE

#240 성능을 위한 쿼리 최적화
  backend/src/services/PostService.ts
  backend/src/utils/Pipeline.ts
  backend/src/utils/index.ts
Labels: BE, API, CLEAN

#242 타임라인 자신 미포함 에러 해결
  backend/src/services/PostService.ts
Labels: BE, API

#241 렌더링 최적화로 인한 버그 대부분 해결
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/LikesButton/index.tsx
  frontend/src/components/buttons/deletes/CommentDeleteButton/index.tsx
  frontend/src/components/buttons/deletes/PostDeleteButton/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/ProfileImage/index.tsx
  frontend/src/components/mains/HomeMain/index.tsx
  frontend/src/components/mains/RandomMain/index.tsx
  frontend/src/components/mains/UserMain/index.tsx
  frontend/src/components/modals/NotificationHeaderModal/index.tsx
  frontend/src/pages/random.tsx
Labels: FIX, FE

#243 Complete! 마지막 버그 수정
  frontend/src/components/buttons/dashboardSettings/DashboardBasicSettingButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardLinkSettingButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardRepoAddButton/index.tsx
  frontend/src/components/buttons/deletes/Common/index.tsx
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/SuggestionCard/style.ts
  frontend/src/components/mains/HomeMain/index.tsx
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/utils/Fetcher.ts
Labels: FE, 완벽

#239 사이트맵 제작
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/sitemap.js
  frontend/src/pages/server-sitemap.xml/index.tsx
  frontend/src/types/env.d.ts
Labels: FE

#245 팔로워 수, 포스트 좋아요 버그 수정
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
Labels: FIX, FE

#246 너무나 방대해지고 힘들어하며 살이 너무 많이 찐 users router 리펙토링 진행 히읗
  backend/src/loaders/routerLoader.ts
  backend/src/routers/v1/users.ts
  backend/src/routers/v1/users/blog.ts
  backend/src/routers/v1/users/dashboard.ts
  backend/src/routers/v1/users/follow.ts
  backend/src/routers/v1/users/index.ts
  backend/src/routers/v1/users/repository.ts
  backend/src/services/UserService.ts
Labels: FIX, BE, API, CLEAN, NOTIFY

#247 컴포넌트 전체적인 리팩토링
  frontend/src/components/Comment/index.tsx
  frontend/src/components/DashboardJobObjectives/index.tsx
  frontend/src/components/DashboardJobObjectives/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/PostDetail/index.tsx
  frontend/src/components/SkeletonLoading/index.tsx
  frontend/src/components/buttons/FollowSetButton/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/buttons/ProfileButton/index.tsx
  frontend/src/components/buttons/ProfileButton/style.ts
  frontend/src/components/buttons/UpdateLanguageStatisticsButton/index.tsx
  frontend/src/components/buttons/UpdateProblemStatisticsButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardRepoAddButton/index.tsx
  frontend/src/components/buttons/deletes/CommentDeleteButton/index.tsx
  frontend/src/components/buttons/deletes/JobObjectiveDeleteButton/index.tsx
  frontend/src/components/buttons/deletes/RepoDeleteButton/index.tsx
  frontend/src/components/buttons/deletes/TechStackDeleteButton/index.tsx
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/heads/PostHead/index.tsx
  frontend/src/components/images/PreviewImages/index.tsx
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/components/inputs/Common/index.tsx
  frontend/src/components/inputs/ImageInput/index.tsx
  frontend/src/components/inputs/UserSearchInput/index.tsx
  frontend/src/components/modals/BlogsModal/index.tsx
  frontend/src/components/modals/DashboardBasicSettingModal/index.tsx
  frontend/src/components/modals/DashboardLinkSettingModal/index.tsx
  frontend/src/components/modals/DashboardProblemStatisticsSettingModal/index.tsx
  frontend/src/components/modals/DashboardRepoAddModal/index.tsx
  frontend/src/components/modals/DashboardTechStacksSettingModal/index.tsx
  frontend/src/components/modals/NotificationHeaderModal/index.tsx
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/components/modals/SearchedTechStacksModal/index.tsx
  frontend/src/components/modals/UsersModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/styles/theme.ts
Labels: FE, CLEAN

#249 스트레스 테스트 스크립트 및 라우터 추가
  backend/package-lock.json
  backend/package.json
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/posts/comment.ts
  backend/src/routers/v1/posts/index.ts
  backend/src/routers/v1/posts/like.ts
  backend/src/test/stress/get_random_timeline_no_query_tuning.bat
  backend/src/test/stress/get_random_timeline_query_tuning.bat
  backend/src/test/stress/get_random_timeline_script/get_random_timeline1.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline128.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline16.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline2.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline256.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline32.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline4.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline64.yaml
  backend/src/test/stress/get_random_timeline_script/get_random_timeline8.yaml
  backend/src/test/stress/get_timeline_no_query_tuning.bat
  backend/src/test/stress/get_timeline_query_tuning.bat
  backend/src/test/stress/get_timeline_script/get_timeline1.yaml
  backend/src/test/stress/get_timeline_script/get_timeline128.yaml
  backend/src/test/stress/get_timeline_script/get_timeline16.yaml
  backend/src/test/stress/get_timeline_script/get_timeline2.yaml
  backend/src/test/stress/get_timeline_script/get_timeline256.yaml
  backend/src/test/stress/get_timeline_script/get_timeline32.yaml
  backend/src/test/stress/get_timeline_script/get_timeline4.yaml
  backend/src/test/stress/get_timeline_script/get_timeline64.yaml
  backend/src/test/stress/get_timeline_script/get_timeline8.yaml
  backend/src/test/stress/no_query_tuning/random_timeline/report/.keep
  backend/src/test/stress/no_query_tuning/random_timeline/result/.keep
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline1.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline128.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline16.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline2.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline256.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline32.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline4.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline64.html
  backend/src/test/stress/no_query_tuning/random_timeline/result/get_random_timeline8.html
  backend/src/test/stress/no_query_tuning/timeline/report/.keep
  backend/src/test/stress/no_query_tuning/timeline/result/.keep
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline1.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline128.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline16.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline2.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline256.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline32.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline4.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline64.html
  backend/src/test/stress/no_query_tuning/timeline/result/get_timeline8.html
  backend/src/test/stress/query_tuning/random_timeline/report/.keep
  backend/src/test/stress/query_tuning/random_timeline/result/.keep
  backend/src/test/stress/query_tuning/random_timeline/script/.keep
  backend/src/test/stress/query_tuning/timeline/report/.keep
  backend/src/test/stress/query_tuning/timeline/result/.keep
Labels: BE, API
