Repository boostcampwm-2021/WEB26-COKIRI, pull requests merged in 2021-11, with the labels that each got.

#5 Post 스키마 및 모델 생성
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/loaders/mongooseLoader.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
Labels: enhancement, backend

#6 Next.js를 위한 styled component 설정
  frontend/.babelrc
  frontend/src/components/FloatingButton/index.tsx
  frontend/src/components/FloatingButton/style.ts
  frontend/src/components/UsersRecommendation/index.tsx
  frontend/src/components/UsersRecommendation/style.ts
  frontend/src/pages/_document.tsx
  frontend/src/pages/home.tsx
Labels: enhancement, frontend

#8 [Backend] 기본적인 구조 설정
  .github/pull_request_template.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/loaders/index.ts
  backend/src/loaders/routerLoader.ts
  backend/src/routers/index.ts
  backend/src/routers/v1/index.ts
  backend/src/routers/v1/posts/index.ts
  backend/src/routers/v1/users/index.ts
  backend/src/services/PostService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
Labels: backend

#9 이모션 설정 및 전역 스타일 설정
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/style.ts
  frontend/src/components/FloatingButton/index.tsx
  frontend/src/components/FloatingButton/style.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/RecommendationCard/index.tsx
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/UsersRecommendation/index.tsx
  frontend/src/components/UsersRecommendation/style.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/echo/[roomID].tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/home/index.tsx
  frontend/src/pages/home/style.ts
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/setting.tsx
  frontend/src/pages/story/[storyID].tsx
  frontend/src/pages/users/[userID].tsx
  frontend/src/styles/global.ts
  frontend/src/styles/globals.css
  frontend/src/styles/index.ts
  frontend/src/styles/theme.ts
Labels: frontend, layout

#10 Users 스키마 설정
  backend/src/bin/www.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/types/modelType.ts
  backend/src/utils/Validate.ts
  backend/src/utils/index.ts
Labels: enhancement, backend

#13 model 구현 및 routing-controllers 적용 등
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/loaders/routerLoader.ts
  backend/src/models/EchoRoom.ts
  backend/src/models/Language.ts
  backend/src/models/Tag.ts
  backend/src/models/index.ts
  backend/src/routers/index.ts
  backend/src/routers/v1/index.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/posts/index.ts
  backend/src/routers/v1/users.ts
  backend/src/routers/v1/users/index.ts
  backend/src/types/index.ts
  backend/src/types/modelType.ts
  backend/tsconfig.json
Labels: backend

#12 헤더 스타일 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/logo.svg
  frontend/src/components/Card/style.ts
  frontend/src/components/FloatingButton/index.tsx
  frontend/src/components/Grid/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/buttons/FloatingButton/index.tsx
  frontend/src/components/buttons/FloatingButton/style.ts
  frontend/src/components/buttons/IconButton/index.tsx
  frontend/src/components/buttons/IconButton/style.ts
  frontend/src/components/buttons/LogoButton/index.tsx
  frontend/src/components/buttons/LogoButton/style.ts
  frontend/src/components/buttons/NavigateButton/index.tsx
  frontend/src/components/buttons/NavigateButton/style.ts
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/home/index.tsx
  frontend/src/pages/home/style.ts
Labels: frontend, layout

#14 리코일 설정 및 리팩토링
  .idea/.gitignore
  .idea/WEB26-COKIRI.iml
  .idea/modules.xml
  .idea/vcs.xml
  frontend/README.md
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/style.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/story/[storyID].tsx
  frontend/src/styles/pages/home.ts
Labels: frontend

#16 헤더 컴포넌트 추가 변경
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SearchBox/style.ts
  frontend/src/components/buttons/IconButton/index.tsx
  frontend/src/components/buttons/IconButton/style.ts
  frontend/src/components/buttons/LogoButton/style.ts
  frontend/src/components/buttons/NavigateButton/style.ts
Labels: frontend, layout

#15 Google Oauth 로그인과 jwt 토큰 발급
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/loaders/index.ts
  backend/src/loaders/passportLoader.ts
  backend/src/models/Language.ts
  backend/src/models/User.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/types/express/index.d.ts
  backend/src/types/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/JWT.ts
  backend/src/utils/Validate.ts
  backend/src/utils/index.ts
  backend/tsconfig.json
Labels: enhancement, backend

#17 CORS 설정
  backend/package-lock.json
  backend/package.json
  backend/src/loaders/corsLoader.ts
  backend/src/loaders/index.ts
Labels: backend

#18 로그인 폼 제작, 구글 로그인 연동 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Card/style.ts
  frontend/src/components/Grid/index.ts
  frontend/src/components/Header/style.ts
  frontend/src/components/RecommendationCard/index.tsx
  frontend/src/components/SearchBox/style.ts
  frontend/src/components/SigninCard/index.tsx
  frontend/src/components/buttons/socials/Common/index.tsx
  frontend/src/components/buttons/socials/Common/style.ts
  frontend/src/components/buttons/socials/Github/index.tsx
  frontend/src/components/buttons/socials/Google/index.tsx
  frontend/src/components/buttons/socials/Kakao/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/styles/global.ts
  frontend/src/utils/.keep
  frontend/src/utils/Fetcher.ts
  frontend/src/utils/index.ts
Labels: frontend, layout

#19 사용자 정보 API 추가
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/types/express/index.d.ts
Labels: backend, api

#20 timeline 컴포넌트 구조 잡기
  frontend/.gitignore
  frontend/src/components/Grid/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Post/Content/index.tsx
  frontend/src/components/Post/Content/style.ts
  frontend/src/components/Post/Image/index.tsx
  frontend/src/components/Post/Image/style.ts
  frontend/src/components/Post/LikeRow/index.tsx
  frontend/src/components/Post/LikeRow/style.ts
  frontend/src/components/Post/Review/index.tsx
  frontend/src/components/Post/Review/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/style.ts
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/Timeline/style.ts
  frontend/src/components/buttons/IconButton/style.ts
  frontend/src/components/buttons/ImageButton/index.tsx
  frontend/src/components/buttons/ImageButton/style.ts
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/buttons/ProfileImageButton/style.ts
  frontend/src/components/buttons/post/CommentButton/index.tsx
  frontend/src/components/buttons/post/CommentButton/style.ts
  frontend/src/components/buttons/post/EchoButton/index.tsx
  frontend/src/components/buttons/post/EchoButton/style.ts
  frontend/src/components/buttons/post/LikeButton/index.tsx
  frontend/src/components/buttons/post/LikeButton/style.ts
  frontend/src/styles/global.ts
Labels: frontend, layout

#21 users api 추가 구현
  backend/src/loaders/passportLoader.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/types/express/index.d.ts
  backend/src/types/modelType.ts
  backend/src/utils/ObjectID.ts
Labels: backend, api

#23 헤더 버튼 크기 조정
  frontend/src/components/buttons/ImageButton/style.ts
  frontend/src/components/buttons/NavigateButton/style.ts
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/echo/[roomID].tsx
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/setting.tsx
  frontend/src/pages/users/[userID].tsx
Labels: frontend, layout

#22 post 관련 API 구현
  backend/.eslintrc.json
  backend/src/models/EchoRoom.ts
  backend/src/models/Language.ts
  backend/src/models/Post.ts
  backend/src/models/Tag.ts
  backend/src/models/User.ts
  backend/src/routers/v1/posts.ts
  backend/src/services/CommentService.ts
  backend/src/services/PostService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
Labels: backend, api

#24 스키마 변경
  backend/src/loaders/passportLoader.ts
  backend/src/models/EchoRoom.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/routers/v1/users.ts
  backend/src/services/PostService.ts
  backend/src/services/UserService.ts
  backend/src/types/modelType.ts
  backend/src/utils/ObjectID.ts
  backend/src/utils/index.ts
Labels: bug, backend

#25 PostService 에러 해결
  backend/src/services/PostService.ts
Labels: backend, api

#27 스키마 Reference Object Id 유효성 검사 추가
  backend/src/models/EchoRoom.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/utils/Validate.ts
Labels: backend

#28 유저 API 변경 및 버그 수정
  backend/src/models/User.ts
  backend/src/services/UserService.ts
  backend/src/types/index.ts
Labels: bug, enhancement, backend, api

#29 유저 정보 업데이트 response 수정, isregistered 반영
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
Labels: backend, api

#30 인증 기능 다지기1
  frontend/.eslintrc.json
  frontend/src/components/SearchBox/style.ts
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/socials/Common/index.tsx
  frontend/src/components/buttons/socials/Github/index.tsx
  frontend/src/components/buttons/socials/Google/index.tsx
  frontend/src/components/buttons/socials/Kakao/index.tsx
  frontend/src/components/cards/Common/index.tsx
  frontend/src/components/cards/Common/style.ts
  frontend/src/components/cards/RecommendationCard/index.tsx
  frontend/src/components/cards/SigninCard/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/home.tsx
  frontend/src/recoil/user/atom.ts
  frontend/src/recoil/user/index.ts
  frontend/src/recoil/user/isAuthenticated.ts
  frontend/src/recoil/user/isRegistered.ts
  frontend/src/styles/global.ts
  frontend/src/types/index.ts
  frontend/src/types/state.ts
  frontend/src/types/user.ts
  frontend/src/utils/Fetcher.ts
Labels: enhancement, frontend, layout

#33 포스트 이미지 컴포넌트 구조 구현 및 폴더 구조 리팩토링
  frontend/src/components/Post/Image/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostContent/index.tsx
  frontend/src/components/PostContent/style.ts
  frontend/src/components/PostImage/index.tsx
  frontend/src/components/PostImage/style.ts
  frontend/src/components/PostLike/index.tsx
  frontend/src/components/PostLike/style.ts
  frontend/src/components/PostProfile/index.tsx
  frontend/src/components/PostProfile/style.ts
  frontend/src/components/PostReview/index.tsx
  frontend/src/components/PostReview/style.ts
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/CommentButton/index.tsx
  frontend/src/components/buttons/CommentButton/style.ts
  frontend/src/components/buttons/EchoButton/index.tsx
  frontend/src/components/buttons/EchoButton/style.ts
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/buttons/LikeButton/style.ts
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/buttons/UserNameButton/index.tsx
  frontend/src/components/buttons/UserNameButton/style.ts
  frontend/src/components/buttons/slides/Common/index.tsx
  frontend/src/components/buttons/slides/Common/style.ts
  frontend/src/components/buttons/slides/LeftSlideButton/index.tsx
  frontend/src/components/buttons/slides/LeftSlideButton/style.ts
  frontend/src/components/buttons/slides/RightSlideButton/index.tsx
  frontend/src/components/buttons/slides/RightSlideButton/style.ts
Labels: frontend, layout

#34 인증 기능 다지기2
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/recoil/user/index.ts
  frontend/src/recoil/user/isRegistered.ts
  frontend/src/types/user.ts
  frontend/src/utils/Fetcher.ts
Labels: enhancement, frontend

#32 post 1순위 API 구현 완료
  backend/src/routers/v1/posts.ts
  backend/src/services/CommentService.ts
  backend/src/services/PostService.ts
Labels: backend, api

#36 컨벤션 및 게시글 title 옵션 수정
  backend/src/models/EchoRoom.ts
  backend/src/models/Language.ts
  backend/src/models/Post.ts
  backend/src/models/Tag.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/socials.ts
  backend/src/services/CommentService.ts
  backend/src/services/PostService.ts
  backend/src/services/UserService.ts
Labels: backend

#37 유저 추가 api 등록
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
Labels: backend, api

#39 포스트 작성 레이아웃 제작 및 API 연결
  frontend/.eslintrc.json
  frontend/src/components/ImagesPreview/index.tsx
  frontend/src/components/ImagesPreview/style.ts
  frontend/src/components/buttons/FloatingButton/index.tsx
  frontend/src/components/buttons/FloatingButton/style.ts
  frontend/src/components/buttons/ImageUploadButton/index.tsx
  frontend/src/components/buttons/ImageUploadButton/style.ts
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/styles/global.ts
  frontend/src/utils/Fetcher.ts
Labels: enhancement, frontend, layout

#38 알고리즘 문제 관련 API 추가 및 Refactor
  backend/package-lock.json
  backend/package.json
  backend/src/models/User.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/users.ts
  backend/src/services/ProblemService.ts
  backend/src/services/UserService.ts
  backend/src/utils/Enums.ts
  backend/src/utils/JWT.ts
  backend/src/utils/ObjectID.ts
  backend/src/utils/Validate.ts
  backend/src/utils/index.ts
Labels: backend, api

#41 post API 데이터 형태 변경
  backend/src/models/Post.ts
  backend/src/types/modelType.ts
Labels: backend

#43 이미지 오브젝트 스토리지에 올리기 기능 구현
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ImagesPreview/index.tsx
  frontend/src/components/buttons/ImageUploadButton/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/utils/Fetcher.ts
  frontend/src/utils/Uploader.ts
  frontend/src/utils/index.ts
Labels: enhancement, frontend, api

#40 포스트 컨텐트 컴포넌트 구조 잡기
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostContent/index.tsx
  frontend/src/components/PostContent/style.ts
  frontend/src/components/PostLongContent/index.tsx
  frontend/src/components/PostLongContent/style.ts
  frontend/src/types/comment.ts
  frontend/src/types/post.ts
Labels: frontend, layout

#44 스키마 validator 방식 변경
  backend/src/models/EchoRoom.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/utils/Validate.ts
Labels: backend

#42 좋아요 리스트 모달 보기 버튼 컴포넌트 구조 잡기
  frontend/src/components/Header/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostContent/style.ts
  frontend/src/components/PostImage/index.tsx
  frontend/src/components/PostImages/index.tsx
  frontend/src/components/PostImages/style.ts
  frontend/src/components/PostLike/index.tsx
  frontend/src/components/PostLongContent/style.ts
  frontend/src/components/PostProfile/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/Profile/style.ts
  frontend/src/components/buttons/FollowButton/index.tsx
  frontend/src/components/buttons/FollowButton/style.ts
  frontend/src/components/buttons/LikeListButton/index.tsx
  frontend/src/components/buttons/LikeListButton/style.ts
  frontend/src/components/buttons/slides/Common/index.tsx
  frontend/src/components/buttons/slides/LeftSlideButton/index.tsx
  frontend/src/components/buttons/slides/RightSlideButton/index.tsx
  frontend/src/components/modals/LikeListModal/index.tsx
  frontend/src/components/modals/LikeListModal/style.ts
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/echo/[roomID].tsx
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/setting.tsx
  frontend/src/pages/story/[storyID].tsx
  frontend/src/pages/users/[userID].tsx
  frontend/src/utils/descriptions.ts
Labels: frontend, layout

#46 스키마 변경....
  backend/src/models/Notify.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
  backend/src/routers/v1/users.ts
  backend/src/services/UserService.ts
  backend/src/types/modelType.ts
  backend/src/utils/Validate.ts
Labels: backend, api

#48 타임라인 API 연동
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostImages/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/LikeListButton/index.tsx
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/buttons/UsernameButton/index.tsx
  frontend/src/components/buttons/UsernameButton/style.ts
  frontend/src/components/modals/LikeListModal/index.tsx
  frontend/src/components/modals/LikeListModal/style.ts
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/types/post.ts
  frontend/src/utils/Fetcher.ts
Labels: enhancement, frontend, api

#47 깃관련 API 구현
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/loaders/gitPassportLoaders.ts
  backend/src/loaders/index.ts
  backend/src/models/Post.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/GitService.ts
  backend/src/services/PostService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
Labels: backend, api

#49 포스트 관련 레이아웃 수정 및 폴더 리팩토링
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/style.ts
  frontend/src/components/PostImages/index.tsx
  frontend/src/components/PostImages/style.ts
  frontend/src/components/ProfileSet/index.tsx
  frontend/src/components/ProfileSet/style.ts
  frontend/src/components/cards/Common/style.ts
  frontend/src/components/modals/LikeListModal/index.tsx
Labels: frontend, layout

#51 tistory 오픈 api 기능 추가 및 프론트 요청 적용
  backend/src/loaders/index.ts
  backend/src/loaders/passportGithubLoader.ts
  backend/src/loaders/passportGoogleLoader.ts
  backend/src/loaders/passportJWTLoader.ts
  backend/src/loaders/passportLoader.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/PostService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/Enums.ts
  backend/src/utils/MongooseParse.ts
  backend/src/utils/Query.ts
  backend/src/utils/index.ts
Labels: bug, enhancement, backend, api

#56 빌드 에러 부분 수정
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
Labels: bug, frontend

#62 MongoDB 전체적인 스키마 변경
  backend/package-lock.json
  backend/package.json
  backend/src/models/Comment.ts
  backend/src/models/CommentLike.ts
  backend/src/models/DashboardHistory.ts
  backend/src/models/DashboardPost.ts
  backend/src/models/EchoMessage.ts
  backend/src/models/EchoRoom.ts
  backend/src/models/Follow.ts
  backend/src/models/Image.ts
  backend/src/models/Notify.ts
  backend/src/models/Post.ts
  backend/src/models/PostLike.ts
  backend/src/models/Tag.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/CommentLikeService.ts
  backend/src/services/CommentService.ts
  backend/src/services/FollowService.ts
  backend/src/services/GitService.ts
  backend/src/services/ImageService.ts
  backend/src/services/PostLikeService.ts
  backend/src/services/PostService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/Enums.ts
  backend/src/utils/Validate.ts
Labels: bug, backend, api

#67 이미지 API 변경으로 인한 이미지 타입 생성 및 적용
  frontend/src/components/PostImages/index.tsx
  frontend/src/types/image.ts
  frontend/src/types/index.ts
Labels: frontend, layout

#69 포스트 타입 안에 images 타입 수정
  frontend/src/types/post.ts
Labels: frontend

#72 인증 후 redirect uri 커스텀
  backend/src/routers/v1/socials.ts
  backend/src/utils/Enums.ts
Labels: backend, api

#73 이미지 프리뷰 컴포넌트 버그 잡기
  frontend/src/components/ImagesPreview/style.ts
  frontend/src/components/buttons/FollowButton/index.tsx
  frontend/src/components/inputs/ImageInput/index.tsx
Labels: bug, frontend, layout

#70 프로필 이미지, 프로필 이미지 버튼 나누기
  frontend/src/components/ProfileImage/index.tsx
  frontend/src/components/ProfileImage/style.ts
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/globals/constants.ts
Labels: frontend, refactoring

#74 images 폴더 분류
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/PostImages/style.ts
  frontend/src/components/images/PreviewImages/index.tsx
  frontend/src/components/images/PreviewImages/style.ts
  frontend/src/components/images/ProfileImage/index.tsx
  frontend/src/components/images/ProfileImage/style.ts
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
Labels: frontend, refactoring

#75 팔로우 언팔로우 기능 Client Side Rendering
  frontend/src/components/buttons/FollowButton/index.tsx
  frontend/src/components/buttons/UnfollowButton/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/globals/constants.ts
Labels: enhancement, frontend, api, layout

#77 좋아요 버튼 수정
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/modals/LikesModal/index.tsx
  frontend/src/types/like.ts
  frontend/src/utils/Fetcher.ts
Labels: frontend

#79 타입 표기법 수정
  frontend/src/types/comment.ts
  frontend/src/types/image.ts
  frontend/src/types/post.ts
Labels: frontend

#81 Post 게시하면 화면에 반영되도록 수정 잡기
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/recoil/posts/atom.ts
  frontend/src/recoil/posts/index.ts
  frontend/src/types/index.ts
  frontend/src/types/post.ts
  frontend/src/types/return.ts
  frontend/src/utils/Fetcher.ts
Labels: frontend, api

#84 팔로우 0명에게 랜덤 유저 추천 컴포넌트 프로토타입 개발
  frontend/src/components/buttons/Common/index.tsx
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/buttons/IconButton/index.tsx
  frontend/src/components/cards/RecommendationCard/index.tsx
  frontend/src/components/cards/RecommendationCard/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/home.tsx
  frontend/src/utils/Fetcher.ts
Labels: frontend, api, layout

#85 Recommendation -> Suggestion 이름 변경
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/SuggestionCard/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/home.tsx
Labels: frontend, refactoring

#82 깃허브 관련 API 구현
  backend/package-lock.json
  backend/package.json
  backend/src/loaders/passportGithubLoader.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/search.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/CommentLikeService.ts
  backend/src/services/CommentService.ts
  backend/src/services/FollowService.ts
  backend/src/services/GitService.ts
  backend/src/services/PostLikeService.ts
  backend/src/services/PostService.ts
  backend/src/services/ProblemService.ts
  backend/src/services/SearchService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/types/index.ts
  backend/src/utils/Calculate.ts
  backend/src/utils/Constant.ts
  backend/src/utils/Enums.ts
  backend/src/utils/index.ts
Labels: backend, api

#86 댓글 미리 보기 구현
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/modals/LikesModal/index.tsx
  frontend/src/globals/constants.ts
Labels: enhancement, frontend

#87 Follow Unfollow 버튼을 FollowSet으로 묶고 추상화
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/sets/FollowSet/index.tsx
  frontend/src/recoil/user/followers.ts
  frontend/src/recoil/user/follows.ts
  frontend/src/recoil/user/index.ts
Labels: enhancement, frontend, refactoring

#88 Tistory 블로그 연동
  backend/src/models/Blog.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/BlogService.ts
  backend/src/services/CommentService.ts
  backend/src/services/PostService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/Constant.ts
Labels: enhancement, backend, api

#90 Recoil과 Next의 사이 좋아지게 하기 ⭐️
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/components/sets/FollowSet/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/pages/users/[username]/settings.tsx
Labels: enhancement, frontend, refactoring

#89 nullable type 최대한 바깥쪽에 선언
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/CommentLikeButton/index.tsx
  frontend/src/components/modals/LikesModal/index.tsx
  frontend/src/components/sets/ProfileSet/index.tsx
Labels: frontend, refactoring

#91 회원가입 시 후처리 버그 전부 픽스
  frontend/src/components/cards/SigninCard/index.tsx
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/recoil/user/hasFollow.ts
  frontend/src/recoil/user/index.ts
  frontend/src/recoil/user/isRegistered.ts
  frontend/src/utils/Fetcher.ts
Labels: enhancement, frontend, refactoring

#92 잠에들기 전 몽롱한 리팩토링 😪
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/buttons/ProfileImageButton/style.ts
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/components/sets/FollowSet/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/utils/Fetcher.ts
Labels: FE, CLEAN

#94 전역 로딩 인디케이터 추가
  frontend/public/images/loading_image.gif
  frontend/src/components/LoadingIndicator/index.tsx
  frontend/src/components/LoadingIndicator/style.ts
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
Labels: FIX, FE, UI/UX

#95 랜덤 페이지 프로토타입 구현
  frontend/src/components/Timeline/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/echo/[roomID].tsx
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/story/[storyID].tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/pages/users/[username]/settings.tsx
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#97 velog 인증 기능 추가 및 issue 해결
  backend/package-lock.json
  backend/package.json
  backend/src/models/Blog.ts
  backend/src/models/Post.ts
  backend/src/models/User.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/socials.ts
  backend/src/services/BlogService.ts
  backend/src/services/CommentLikeService.ts
  backend/src/services/PostService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/services/VelogService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/Constant.ts
  backend/src/utils/Mailer.ts
  backend/src/utils/MongooseParse.ts
  backend/src/utils/Validate.ts
  backend/src/utils/index.ts
Labels: FIX, FEAT, BE, API

#98 검색 기능 구현 (쓰로틀링은 아직 미구현)
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/buttons/UsernameButton/index.tsx
  frontend/src/components/buttons/UsernameButton/style.ts
  frontend/src/components/inputs/Common/index.tsx
  frontend/src/components/inputs/SearchInput/index.tsx
  frontend/src/components/modals/HeaderModal/index.tsx
  frontend/src/components/modals/HeaderModal/style.ts
  frontend/src/utils/Fetcher.ts
Labels: FE, API, UI/UX

#100 댓글 리로드 수정 및 좋아요 리스트 모달 수정
  frontend/src/components/modals/LikesModal/index.tsx
Labels: FIX, FE

#99 오브젝트 스토리지 삭제 적용 및 mongoose 메소드 변경
  backend/package-lock.json
  backend/package.json
  backend/src/models/DashboardRepository.ts
  backend/src/models/Language.ts
  backend/src/models/Notify.ts
  backend/src/models/Post.ts
  backend/src/models/TechStack.ts
  backend/src/models/User.ts
  backend/src/models/index.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/users.ts
  backend/src/services/CommentLikeService.ts
  backend/src/services/CommentService.ts
  backend/src/services/FollowService.ts
  backend/src/services/ImageService.ts
  backend/src/services/NotifyService.ts
  backend/src/services/ObjectStroageService.ts
  backend/src/services/PostLikeService.ts
  backend/src/services/PostService.ts
  backend/src/services/SearchService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
  backend/src/utils/Calculate.ts
  backend/src/utils/Constant.ts
  backend/src/utils/Urlparser.ts
  backend/src/utils/Validate.ts
  backend/src/utils/index.ts
  backend/src/utils/objectStorage.ts
Labels: FEAT, BE, API, CLEAN

#101 포스트 전체 보기 구현
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/DetailPost/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/PostContent/index.tsx
  frontend/src/components/PostContent/style.ts
  frontend/src/components/buttons/CommentButton/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/PostImages/style.ts
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/components/sets/ProfileSet/index.tsx
  frontend/src/components/sets/ProfileSet/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/posts/[postID].tsx
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#103 핫픽스 적용
  backend/src/services/index.ts
Labels: FIX

#104 무한 스크롤 대응 상태값 변경 및 리팩토링
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/FloatingButton/index.tsx
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/inputs/Common/index.tsx
  frontend/src/components/inputs/SearchInput/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/pages/users/[username]/settings.tsx
  frontend/src/recoil/posts/atom.ts
  frontend/src/recoil/posts/index.ts
  frontend/src/utils/Fetcher.ts
Labels: FIX, FE, CLEAN

#105 모든 API 반환값 변경
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/search.ts
  backend/src/routers/v1/users.ts
  backend/src/services/ImageService.ts
  backend/src/services/ObjectStorageService.ts
  backend/src/services/index.ts
  backend/src/utils/index.ts
Labels: BE, API, CLEAN, NOTIFY

#107 nextCursor 형식 변경
  backend/src/routers/v1/posts.ts
  backend/src/services/PostService.ts
Labels: NOTIFY, 급함!

#106 배포를 위한 쿠키 설정 변경
  backend/src/routers/v1/socials.ts
  backend/src/utils/URLparser.ts
  backend/src/utils/index.ts
Labels: NOTIFY, 급함!

#111 깃허브 Repo 리스트 모달 프로토타입 잡기
  frontend/src/components/Grid/index.ts
  frontend/src/components/cards/ExternalAuthCard/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/components/modals/ReposModal/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/users/[username]/settings.tsx
  frontend/src/types/index.ts
  frontend/src/types/repo.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#113 팔로워 팔로우를 볼 수 있게 잡기
  frontend/src/components/buttons/FollowersButton/index.tsx
  frontend/src/components/buttons/FollowsButton/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserInfoCard/style.ts
  frontend/src/components/modals/FollowersModal/index.tsx
  frontend/src/components/modals/FollowsModal/index.tsx
  frontend/src/components/modals/UsersModal/index.tsx
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#112 게시물, 댓글 삭제 기능 구현
  frontend/src/components/Comment/index.tsx
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/buttons/deletes/CommentDeleteButton/index.tsx
  frontend/src/components/buttons/deletes/Common/index.tsx
  frontend/src/components/buttons/deletes/Common/style.ts
  frontend/src/components/buttons/deletes/PostDeleteButton/index.tsx
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/components/modals/DeleteModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/home.tsx
  frontend/src/types/post.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#114 Post 스키마 변경 관련 Refactoring
  backend/src/routers/v1/posts.ts
  backend/src/services/PostService.ts
  backend/src/services/ProblemService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/utils/Constant.ts
Labels: BE, CLEAN

#116 Fix: 인증 순서 변경
  backend/src/routers/v1/socials.ts
Labels: FIX, 급함!

#115 대시보드 관련 API들 구현
  backend/src/loaders/passportGithubLoader.ts
  backend/src/models/DashboardRepository.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/DashboardRepoService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/types/modelType.ts
Labels: FEAT, BE, API, CLEAN

#117 Fix: tistory 인증에 대해서 response 로 uri 을 담겨주는 방식으로 변경
  backend/src/routers/v1/socials.ts
Labels: FIX, BE

#118 포스트 전체적인 스타일 수정
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Comment/style.ts
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/DetailPost/style.ts
  frontend/src/components/Grid/index.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/PostContent/index.tsx
  frontend/src/components/PostContent/style.ts
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/buttons/NavigateIconButton/index.tsx
  frontend/src/components/buttons/slides/LeftSlideButton/index.tsx
  frontend/src/components/buttons/slides/RightSlideButton/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/PostImages/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/posts/[postID].tsx
Labels: FIX, FE, UI/UX

#121 백엔드 이슈 해결
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/search.ts
  backend/src/services/PostService.ts
Labels: BE, API

#125 문제 검색 모달 개발
  frontend/src/components/buttons/Common/index.tsx
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/inputs/SearchInput/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ProblemsModal/style.ts
  frontend/src/globals/constants.ts
  frontend/src/types/index.ts
  frontend/src/types/problem.ts
  frontend/src/utils/Fetcher.ts
Labels: FE, API, UI/UX

#127 버튼 clicked props NavigateIcon과 Header에 적용
  frontend/src/components/Header/index.tsx
  frontend/src/components/buttons/IconButton/index.tsx
  frontend/src/components/buttons/NavigateIconButton/index.tsx
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/users/[username].tsx
Labels: FE, UI/UX

#129 포스트 전체보기 수정
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/DetailPost/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/DetailButton/index.tsx
  frontend/src/components/images/PostImages/index.tsx
  frontend/src/components/images/PostImages/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
Labels: FIX, FE, STYLE

#130 포스트 컨텐트 추상화
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/contents/BaekjoonContent/index.tsx
  frontend/src/components/contents/BlogContent/index.tsx
  frontend/src/components/contents/Common/index.tsx
  frontend/src/components/contents/Common/style.ts
  frontend/src/components/contents/GitHubContent/index.tsx
  frontend/src/components/contents/NormalContent/index.tsx
Labels: FE

#132 몇분전 몇시간 전 을 표시하는 TimeFromNow 컴포넌트 개발
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostComments/index.tsx
  frontend/src/components/TimeFromNow/index.tsx
  frontend/src/components/TimeFromNow/style.ts
  frontend/src/utils/index.ts
  frontend/src/utils/moment.ts
Labels: FEAT, FE

#131 post external 스키마 변경 적용
  backend/src/models/Post.ts
  backend/src/routers/v1/posts.ts
  backend/src/services/CommentService.ts
  backend/src/services/ImageService.ts
  backend/src/services/PostLikeService.ts
  backend/src/services/PostService.ts
  backend/src/services/TistoryService.ts
  backend/src/types/modelType.ts
  backend/src/utils/Constant.ts
Labels: BE, API, CLEAN

#135 알고리즘 문제 세부내용 가져오기 변경
  backend/src/models/Post.ts
  backend/src/routers/v1/problems.ts
  backend/src/services/ProblemService.ts
  backend/src/utils/Constant.ts
Labels: BE, API, CLEAN

#136 스키마 변경 및 타임라인 nextCursor 게시글 인덱스로 변경
  backend/src/models/TechStack.ts
  backend/src/models/User.ts
  backend/src/routers/v1/posts.ts
  backend/src/services/PostService.ts
  backend/src/types/modelType.ts
Labels: BE, API

#139 포스트 width props 제거
  frontend/src/components/DetailPost/index.tsx
  frontend/src/components/DetailPost/style.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/TimeFromNow/style.ts
  frontend/src/components/contents/BaekjoonContent/index.tsx
  frontend/src/components/contents/BlogContent/index.tsx
  frontend/src/components/contents/Common/index.tsx
  frontend/src/components/contents/Common/style.ts
  frontend/src/components/contents/GitHubContent/index.tsx
  frontend/src/components/contents/NormalContent/index.tsx
  frontend/src/globals/constants.ts
Labels: FE, CLEAN

#142 Fix: 깃허브 유저네임 가져오기 토큰 에러 해결
  backend/src/routers/v1/socials.ts
Labels: BE, API

#144 백준 Problem Content 잡기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Grid/index.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/contents/BaekjoonContent/index.tsx
  frontend/src/components/contents/ExternalContent/index.tsx
  frontend/src/components/contents/ExternalContent/style.ts
  frontend/src/components/contents/GitHubContent/index.tsx
  frontend/src/components/contents/ProblemContent/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/types/external.ts
  frontend/src/types/index.ts
  frontend/src/types/info.ts
  frontend/src/types/post.ts
Labels: FEAT, FE, API, UI/UX

#146 블로그, 레포 컨텐트 컴포넌트 잡기
  frontend/src/components/contents/BlogContent/index.tsx
  frontend/src/components/contents/ExternalContent/index.tsx
  frontend/src/components/contents/ProblemContent/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/types/external.ts
  frontend/src/types/info.ts
Labels: FE, API, UI/UX

#143 요구사항에 적용 및 리펙토링
  backend/src/models/DashboardRepository.ts
  backend/src/models/Post.ts
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/search.ts
  backend/src/routers/v1/users.ts
  backend/src/services/BlogService.ts
  backend/src/services/CommentService.ts
  backend/src/services/GitService.ts
  backend/src/services/PostService.ts
  backend/src/services/ProblemService.ts
  backend/src/services/TistoryService.ts
  backend/src/services/UserService.ts
  backend/src/types/modelType.ts
  backend/src/utils/Constant.ts
Labels: BE, CLEAN

#150 카카오 OAuth 인증
  backend/package-lock.json
  backend/package.json
  backend/src/loaders/index.ts
  backend/src/loaders/passportKakaoLoader.ts
  backend/src/routers/v1/socials.ts
Labels: BE, API

#151 Refactor: 백준 상대경로 이미지 정규식과 replace 적용
  backend/src/services/ProblemService.ts
  backend/src/utils/Constant.ts
Labels: FIX, BE, API

#148 비회원으로 접속할 경우 레이아웃 예외 처리
  frontend/src/components/Header/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/components/modals/SigninModal/index.tsx
  frontend/src/components/modals/UsersModal/index.tsx
  frontend/src/components/sets/FollowSet/index.tsx
  frontend/src/components/sets/ProfileSet/index.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/utils/moment.ts
Labels: FIX, FEAT, FE

#157 전반 적인 리팩토링 및 팔로우 추천 버그 수정
  frontend/src/components/buttons/FollowersButton/index.tsx
  frontend/src/components/buttons/socials/Github/index.tsx
  frontend/src/components/buttons/socials/Kakao/index.tsx
  frontend/src/components/cards/SuggestionCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/globals/descriptions.ts
  frontend/src/pages/home.tsx
  frontend/src/pages/users/[username].tsx
Labels: FE, CLEAN

#149 알고리즘 통계정보 가져오기
  backend/src/models/User.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/users.ts
  backend/src/services/GitService.ts
  backend/src/services/ProblemService.ts
  backend/src/services/UserService.ts
  backend/src/services/VelogService.ts
  backend/src/types/modelType.ts
  backend/src/utils/Constant.ts
Labels: BE, API

#155 대시보드 프로토타입 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PostDetail/index.tsx
  frontend/src/components/PostDetail/style.ts
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/buttons/UsernameButton/style.ts
  frontend/src/components/buttons/dashboardSettings/Common/index.tsx
  frontend/src/components/buttons/dashboardSettings/GitHubRepoAddButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/HistoryAddButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/UserInfoSettingButton/index.tsx
  frontend/src/components/cards/DashboardGithubRepoCard/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/style.ts
  frontend/src/components/cards/DashboardLinkCard/index.tsx
  frontend/src/components/cards/DashboardStackCard/index.tsx
  frontend/src/components/cards/DashboardStackCard/style.ts
  frontend/src/components/cards/DashboardStatisticsCard/index.tsx
  frontend/src/components/cards/DashboardUserInfoCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/charts/Radar/index.tsx
  frontend/src/components/contents/ExternalContent/style.ts
  frontend/src/components/images/ProfileImage/index.tsx
  frontend/src/components/images/ProfileImage/style.ts
  frontend/src/components/modals/GitHubRepoAddModal/index.tsx
  frontend/src/components/modals/HistoryAddModal/index.tsx
  frontend/src/components/modals/UserInfoSettingModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/dashboard.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/styles/global.ts
  frontend/src/utils/index.ts
  frontend/src/utils/options.ts
Labels: FE, UI/UX

#160 nextCursor 문제 해결
  backend/src/routers/v1/posts.ts
  backend/src/services/PostService.ts
Labels: BE, API

#159 소셜 인증과정에 기타 예외 발생으로 인한 피알입니다ㅠㅠㅠㅠㅠㅠㅠㅠㅠ
  backend/src/loaders/passportGithubLoader.ts
  backend/src/loaders/passportGoogleLoader.ts
  backend/src/loaders/passportJWTLoader.ts
  backend/src/loaders/passportKakaoLoader.ts
  backend/src/routers/v1/socials.ts
  backend/src/utils/Authorization.ts
  backend/src/utils/JWT.ts
  backend/src/utils/index.ts
  backend/src/utils/objectStorage.ts
Labels: BE, CLEAN, NOTIFY

#153 대시보드 기능 추가 및 검증
  backend/src/models/User.ts
  backend/src/routers/v1/problems.ts
  backend/src/routers/v1/users.ts
  backend/src/services/DashboardHistoryService.ts
  backend/src/services/UserService.ts
  backend/src/services/index.ts
  backend/src/utils/Constant.ts
  backend/src/utils/Validate.ts
Labels: BE, API

#162 🌟 무한 🌟 스크롤 구현
  frontend/src/components/Timeline/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/hooks/IntersectionObserver.ts
  frontend/src/hooks/index.ts
  frontend/src/pages/home.tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/types/return.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE, API, 완벽

#166 Fix: 회원가입 모달 뜨는 조건 수정
  frontend/src/components/modals/RegisterModal/index.tsx
Labels: FIX, 급함!

#163 깃허브 언어 통계 API get, put 분리
  backend/src/routers/v1/users.ts
  backend/src/services/DashboardRepoService.ts
Labels: BE, API

#169 프론트 요구사항 응답 타입 변경
  backend/src/models/Post.ts
  backend/src/routers/v1/users.ts
  backend/src/services/PostService.ts
  backend/src/services/ProblemService.ts
  backend/src/services/TistoryService.ts
  backend/src/types/modelType.ts
Labels: BE, API, CLEAN

#167 로그아웃 및 레포 리스트 늘리기
  backend/src/routers/v1/users.ts
  backend/src/utils/Authorization.ts
  backend/src/utils/Constant.ts
Labels: BE, API

#170 외부 연동 작성 잡기1
  frontend/src/components/buttons/Common/index.tsx
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/cards/ExternalAuthCard/index.tsx
  frontend/src/components/inputs/ImageInput/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ProblemsModal/style.ts
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/components/modals/ReposModal/style.ts
  frontend/src/types/repo.ts
  frontend/src/utils/Fetcher.ts
Labels: FE, API, UI/UX

#168 유저 정보 api 연결1
  frontend/src/components/buttons/dashboardSettings/DashboardHistoryAddButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardRepoAddButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardUserInfoSettingButton/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/index.tsx
  frontend/src/components/cards/DashboardLinkCard/index.tsx
  frontend/src/components/cards/DashboardRepoCard/index.tsx
  frontend/src/components/cards/DashboardStackCard/index.tsx
  frontend/src/components/cards/DashboardStackCard/style.ts
  frontend/src/components/cards/DashboardUserInfoCard/index.tsx
  frontend/src/components/modals/RepoAddModal/index.tsx
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/types/index.ts
  frontend/src/types/info.ts
  frontend/src/types/stack.ts
  frontend/src/utils/Fetcher.ts
Labels: FE

#171 자신의 정보 가져오기 데이터 추가
  backend/src/routers/v1/posts.ts
  backend/src/routers/v1/users.ts
  backend/src/services/BlogService.ts
  backend/src/services/UserService.ts
Labels: BE, API

#172 languageInfo 없는 레포에 대한 예외처리
  backend/src/services/GitService.ts
Labels: FIX, BE, API

#173 프론트 요구사항 수용으로 인한 post 스키마 변경
  backend/src/models/Post.ts
  backend/src/services/PostService.ts
  backend/src/types/modelType.ts
Labels: BE, API, 급함!

#175 findRepo 서비스 코드 에러처리
  backend/src/services/GitService.ts
  backend/src/utils/Constant.ts
Labels: FIX, BE, API

#177 cursor 관련 문제 해결 및 리팩토링
  backend/src/routers/v1/users.ts
  backend/src/services/PostService.ts
  backend/src/utils/Cursor.ts
Labels: FIX, BE, API, CLEAN

#174 외부 연동 작성 잡기2
  frontend/src/components/Post/index.tsx
  frontend/src/components/buttons/FloatingButton/index.tsx
  frontend/src/components/contents/ExternalContent/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/types/post.ts
  frontend/src/types/repo.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE, API

#179 리팩토링 및 예외처리 부분 진행 (UserService 코드 위주)
  backend/src/loaders/passportJWTLoader.ts
  backend/src/routers/v1/socials.ts
  backend/src/routers/v1/users.ts
  backend/src/services/DashboardRepoService.ts
  backend/src/services/UserService.ts
Labels: FIX, BE, CLEAN

#182 로그아웃 jwt 인증 제거
  backend/src/routers/v1/users.ts
Labels: FIX, BE

#184 Fix: Tistory 인증 관련 에러 해결
  backend/src/routers/v1/socials.ts
Labels: FIX, BE

#185 비회원일 경우 레이아웃 변경하기 + 리팩토링
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostDetail/index.tsx
  frontend/src/components/PostDetail/style.ts
  frontend/src/components/buttons/CommentLikeButton/index.tsx
  frontend/src/components/buttons/EchoButton/index.tsx
  frontend/src/components/buttons/EchoButton/style.ts
  frontend/src/components/buttons/IconButton/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/components/inputs/CommentInput/index.tsx
  frontend/src/pages/echo/[roomID].tsx
  frontend/src/pages/echo/index.tsx
  frontend/src/pages/story/[storyID].tsx
Labels: FIX, FE, API, STYLE

#181 유저 정보 api 연결2
  frontend/src/components/buttons/dashboardSettings/DashboardUserInfoSettingButton/index.tsx
  frontend/src/components/cards/DashboardLinkCard/index.tsx
  frontend/src/components/cards/DashboardStatisticsCard/index.tsx
  frontend/src/components/cards/DashboardUserInfoCard/index.tsx
  frontend/src/components/cards/DashboardUserInfoCard/style.ts
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/DashboardHistoryAddModal/index.tsx
  frontend/src/components/modals/DashboardRepoAddModal/index.tsx
  frontend/src/components/modals/DashboardUserInfoSettingModal/index.tsx
  frontend/src/components/modals/DashboardUserInfoSettingModal/style.ts
  frontend/src/components/modals/UserInfoSettingModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#186 DashboardBasicCard 구조 분리
  frontend/src/components/buttons/dashboardSettings/DashboardBasicSettingButton/index.tsx
  frontend/src/components/cards/DashboardBasicCard/index.tsx
  frontend/src/components/cards/DashboardBasicCard/style.ts
  frontend/src/components/modals/DashboardBasicSettingModal/index.tsx
  frontend/src/components/modals/DashboardBasicSettingModal/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/recoil/dashboardUserInfo/atom.ts
  frontend/src/recoil/dashboardUserInfo/dashboardHistories.ts
  frontend/src/recoil/dashboardUserInfo/dashboardTechStacks.ts
  frontend/src/recoil/dashboardUserInfo/index.ts
  frontend/src/types/dashboardUserInfo.ts
  frontend/src/types/index.ts
  frontend/src/types/info.ts
Labels: FE

#188 외부 인증 카드 마무리
  frontend/src/components/cards/ExternalAuthCard/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/types/user.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#189 대시보드 히스토리 추가 삭제 구현
  frontend/src/components/buttons/dashboardSettings/DashboardHistoryDeleteButton/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/style.ts
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/DashboardHistoryAddModal/index.tsx
  frontend/src/components/modals/DashboardHistoryAddModal/style.ts
  frontend/src/components/modals/DashboardHistoryDeleteModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/_app.tsx
  frontend/src/recoil/dashboardUserInfo/dashboardHistories.ts
  frontend/src/types/history.ts
  frontend/src/types/index.ts
  frontend/src/utils/Fetcher.ts
  frontend/src/utils/moment.ts
Labels: FEAT, FE

#190 Refactor: 연동된 블로그 글을 가져오는 경우 response format 변경
  backend/src/services/BlogService.ts
Labels: BE

#191 외부 연동 안했을 시의 상황 처리
  frontend/src/components/ExternalPreview/index.tsx
  frontend/src/components/ExternalPreview/style.ts
  frontend/src/components/Grid/index.ts
  frontend/src/components/LoadingIndicator/index.tsx
  frontend/src/components/LoadingIndicator/style.ts
  frontend/src/components/buttons/CommentLikeButton/index.tsx
  frontend/src/components/contents/BlogContent/index.tsx
  frontend/src/components/contents/ExternalContent/index.tsx
  frontend/src/components/contents/ProblemContent/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/components/modals/BlogsModal/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/types/external.ts
Labels: FE, API

#192 Fetcher 메소드 정의
  frontend/src/types/dashboardUserInfo.ts
  frontend/src/types/index.ts
  frontend/src/types/languageStatistics.ts
  frontend/src/types/stack.ts
  frontend/src/types/statistics.ts
  frontend/src/types/user.ts
  frontend/src/utils/Fetcher.ts
Labels: FE

#193 대시보드 버그 나지 않도록 카드 삭제
  frontend/src/components/cards/DashboardBasicCard/index.tsx
  frontend/src/pages/users/[username]/dashboard.tsx
Labels: FE

#194 알림 모달 프로토타입, 포스트에 외부 컨텐트 추가
  frontend/src/components/Header/index.tsx
  frontend/src/components/PostDetail/index.tsx
  frontend/src/components/buttons/NotificationButton/index.tsx
  frontend/src/components/inputs/UserSearchInput/index.tsx
  frontend/src/components/inputs/UserSearchInput/style.ts
  frontend/src/components/modals/HeaderModal/index.tsx
  frontend/src/components/modals/HeaderModal/style.ts
  frontend/src/components/modals/NotificationHeaderModal/index.tsx
  frontend/src/components/modals/NotificationHeaderModal/style.ts
  frontend/src/types/index.ts
  frontend/src/types/notification.ts
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE, API

#195 notify 반환 및 problem 통계 반환 타입 변경
  backend/src/models/Notify.ts
  backend/src/routers/v1/users.ts
  backend/src/services/NotifyService.ts
  backend/src/services/ProblemService.ts
Labels: BE, API

#196 이미지상수를 따로 관리하도록 변경
  frontend/src/components/buttons/LogoButton/index.tsx
  frontend/src/components/buttons/ProfileImageButton/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/components/images/ProfileImage/index.tsx
  frontend/src/components/modals/DashboardBasicSettingModal/index.tsx
  frontend/src/components/sets/ProfileSet/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/globals/images.ts
  frontend/src/pages/home.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/pages/users/[username]/settings.tsx
Labels: FE, CLEAN

#197 오타 수정
  frontend/src/components/cards/DashboardHistoryCard/index.tsx
  frontend/src/components/cards/DashboardHistoryCard/style.ts
  frontend/src/recoil/dashboardUserInfo/dashboardHistories.ts
  frontend/src/types/languageStatistics.ts
  frontend/src/utils/Fetcher.ts
Labels: FE

#201 알림 기능 구현 완료
  frontend/src/components/buttons/NotificationButton/index.tsx
  frontend/src/components/modals/HeaderModal/index.tsx
  frontend/src/components/modals/HeaderModal/style.ts
  frontend/src/components/modals/NotificationHeaderModal/index.tsx
  frontend/src/components/modals/NotificationHeaderModal/style.ts
  frontend/src/globals/images.ts
  frontend/src/types/notification.ts
Labels: FEAT, FE, API

#203 대시보드 링크 카드 구현
  frontend/src/components/DashboardJobObjectives/index.tsx
  frontend/src/components/DashboardJobObjectives/style.ts
  frontend/src/components/buttons/dashboardSettings/DashboardLinkSettingButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/DashboardUserInfoSettingButton/index.tsx
  frontend/src/components/buttons/dashboardSettings/JobObjectiveAddButton/index.tsx
  frontend/src/components/buttons/deletes/JobObjectiveDeleteButton/index.tsx
  frontend/src/components/cards/DashboardLinkCard/index.tsx
  frontend/src/components/cards/DashboardLinkCard/style.ts
  frontend/src/components/modals/DashboardBasicSettingModal/index.tsx
  frontend/src/components/modals/DashboardLinkSettingModal/index.tsx
  frontend/src/components/modals/DashboardLinkSettingModal/style.ts
  frontend/src/globals/constants.ts
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/recoil/user/atom.ts
Labels: FEAT, FE

#204 포스트 디테일 리팩토링, 회원가입 username 유효성 및 중복검사 구현
  frontend/src/components/Grid/index.ts
  frontend/src/components/PostDetail/index.tsx
  frontend/src/components/PostDetail/style.ts
  frontend/src/components/modals/Common/style.ts
  frontend/src/components/modals/NotificationHeaderModal/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/intersectionObserver.ts
  frontend/src/utils/Fetcher.ts
Labels: FE, API, CLEAN

#205 Fetcher 수정
  frontend/src/components/modals/DashboardBasicSettingModal/index.tsx
  frontend/src/components/modals/DashboardLinkSettingModal/index.tsx
  frontend/src/utils/Fetcher.ts
Labels: FE

#202 notify 관련 이슈 해결
  backend/src/services/CommentService.ts
  backend/src/services/NotifyService.ts
Labels: FIX, BE, API

#208 Fix: Like 코드 반대로 적용된거 수정
  backend/src/services/CommentLikeService.ts
  backend/src/services/CommentService.ts
Labels: FIX, BE, API

#206 폰트 적용 및 공통 컴포넌트 props 속성 추가
  frontend/public/fonts/IBMPlexSansKR-Regular.eot
  frontend/public/fonts/IBMPlexSansKR-Regular.ttf
  frontend/public/fonts/IBMPlexSansKR-Regular.woff
  frontend/public/fonts/IBMPlexSansKR-Regular.woff2
  frontend/src/components/Grid/index.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/cards/Common/index.tsx
  frontend/src/components/cards/Common/style.ts
  frontend/src/components/inputs/Common/style.ts
  frontend/src/styles/global.ts
Labels: FEAT, FE, STYLE

#209 인풋 컴포넌트에서 디바운스 이벤트 구현
  frontend/src/components/inputs/Common/index.tsx
  frontend/src/components/inputs/UserSearchInput/index.tsx
  frontend/src/components/modals/LikesModal/index.tsx
  frontend/src/components/modals/LikesModal/style.ts
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/hooks/debounce.ts
  frontend/src/hooks/index.ts
Labels: FEAT, FE, API

#211 대시보드 스택 모달 구현
  frontend/src/components/buttons/dashboardSettings/DashboardTechStacksSettingButton/index.tsx
  frontend/src/components/cards/DashboardStackCard/index.tsx
  frontend/src/components/cards/DashboardTechStacksCard/index.tsx
  frontend/src/components/cards/DashboardTechStacksCard/style.ts
  frontend/src/components/modals/DashboardTechStacksSettingModal/index.tsx
  frontend/src/components/modals/DashboardTechStacksSettingModal/style.ts
  frontend/src/components/modals/SearchedTechStacksModal/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/utils/Fetcher.ts
Labels: FEAT, FE

#212 Grid에서 margin padding 빼고 스타일 대폭 수정
  frontend/src/components/DashboardJobObjectives/index.tsx
  frontend/src/components/ExternalPreview/style.ts
  frontend/src/components/Grid/index.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/PostDetail/style.ts
  frontend/src/components/cards/DashboardBasicCard/index.tsx
  frontend/src/components/cards/DashboardLinkCard/index.tsx
  frontend/src/components/cards/DashboardTechStacksCard/index.tsx
  frontend/src/components/contents/ProblemContent/index.tsx
  frontend/src/components/contents/RepoContent/index.tsx
  frontend/src/components/modals/BlogsModal/index.tsx
  frontend/src/components/modals/BlogsModal/style.ts
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/ProblemsModal/style.ts
  frontend/src/components/modals/ReposModal/index.tsx
  frontend/src/components/modals/ReposModal/style.ts
Labels: FE, API, CLEAN

#213 디자인 대폭 개선 및 리팩토링
  frontend/src/components/ExternalPreview/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/TimeFromNow/style.ts
  frontend/src/components/buttons/CommentLikeButton/index.tsx
  frontend/src/components/buttons/Common/index.tsx
  frontend/src/components/buttons/Common/style.ts
  frontend/src/components/buttons/FollowButton/index.tsx
  frontend/src/components/buttons/LikeButton/index.tsx
  frontend/src/components/buttons/UnfollowButton/index.tsx
  frontend/src/components/cards/UserInfoCard/index.tsx
  frontend/src/components/cards/UserInfoCard/style.ts
  frontend/src/components/inputs/Common/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/LikesModal/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/RegisterModal/index.tsx
  frontend/src/components/modals/SigninModal/index.tsx
  frontend/src/components/modals/UsersModal/index.tsx
  frontend/src/components/modals/UsersModal/style.ts
  frontend/src/components/sets/FollowSet/index.tsx
  frontend/src/globals/constants.ts
  frontend/src/utils/Fetcher.ts
Labels: FE, CLEAN, STYLE

#210 알림 예외처리 추가
  backend/src/services/CommentLikeService.ts
  backend/src/services/CommentService.ts
  backend/src/services/FollowService.ts
  backend/src/services/PostLikeService.ts
Labels: BE, API

#214 전반적인 스타일링 및 리팩토링
  frontend/src/components/cards/ExternalAuthCard/index.tsx
  frontend/src/components/cards/UserSettingsCard/index.tsx
  frontend/src/components/images/PostImages/style.ts
  frontend/src/components/images/PreviewImages/style.ts
  frontend/src/components/modals/BlogsModal/index.tsx
  frontend/src/components/modals/Common/index.tsx
  frontend/src/components/modals/PostWriteModal/index.tsx
  frontend/src/components/modals/PostWriteModal/style.ts
  frontend/src/components/modals/ProblemsModal/index.tsx
  frontend/src/components/modals/UsersModal/index.tsx
  frontend/src/pages/users/[username]/settings.tsx
Labels: FE, UI/UX

#216 Refactor: dashboard response 에 username 정보도 추가
  backend/src/routers/v1/users.ts
  backend/src/utils/ObjectStorage.ts
Labels: 급함!

#217 오픈 그래프 메타 태그 추가 및 대쉬보드 버그 수정
  frontend/public/images/loading_image.gif
  frontend/public/images/logo_background_image.png
  frontend/src/components/Header/index.tsx
  frontend/src/components/contents/Common/index.tsx
  frontend/src/components/contents/NormalContent/index.tsx
  frontend/src/components/contents/NormalContent/style.ts
  frontend/src/components/heads/DashboardHead/index.tsx
  frontend/src/components/heads/HomeHead/index.tsx
  frontend/src/components/heads/PostHead/index.tsx
  frontend/src/components/heads/RandomHead/index.tsx
  frontend/src/components/heads/SettingsHead/index.tsx
  frontend/src/components/heads/UserHead/index.tsx
  frontend/src/components/heads/common/index.tsx
  frontend/src/globals/descriptions.ts
  frontend/src/globals/images.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/posts/[postID].tsx
  frontend/src/pages/random.tsx
  frontend/src/pages/users/[username].tsx
  frontend/src/pages/users/[username]/dashboard.tsx
  frontend/src/pages/users/[username]/settings.tsx
  frontend/src/recoil/dashboardUserInfo/atom.ts
  frontend/src/types/dashboardUserInfo.ts
  frontend/src/utils/Fetcher.ts
Labels: FIX, FE

#218 RecoilRoot 중첩할 시 상위 루트의 값이 내려가지 않는 버그 수정
  frontend/src/pages/users/[username]/dashboard.tsx
Labels: FIX, FE
